// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALB2rTxgr6dQAc4Y9iLKdXfLU4iMZv6Ek',
    appId: '1:834977391795:android:fba7feced40d5172fd3cc6',
    messagingSenderId: '834977391795',
    projectId: 'a1-aone',
    storageBucket: 'a1-aone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW5GNLYNomyzEd23jJz-38QOae6Bvqpoo',
    appId: '1:834977391795:ios:0ca35dc89c4479f6fd3cc6',
    messagingSenderId: '834977391795',
    projectId: 'a1-aone',
    storageBucket: 'a1-aone.firebasestorage.app',
    androidClientId: '834977391795-hc1sh43gq3an49jl1f8pm1jhq35m5tim.apps.googleusercontent.com',
    iosClientId: '834977391795-a8b3smp0ms2devg2hpack7lt5r3f0mhb.apps.googleusercontent.com',
    iosBundleId: 'com.aone.solonetworksns',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLQp_f0TaWMEX8mbzAucqw2GvO2w0Oy78',
    appId: '1:834977391795:web:bd7d53dc4e656d5dfd3cc6',
    messagingSenderId: '834977391795',
    projectId: 'a1-aone',
    authDomain: 'a1-aone.firebaseapp.com',
    storageBucket: 'a1-aone.firebasestorage.app',
    measurementId: 'G-K6DWZKMB3V',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW5GNLYNomyzEd23jJz-38QOae6Bvqpoo',
    appId: '1:834977391795:ios:6df52fbb031bd019fd3cc6',
    messagingSenderId: '834977391795',
    projectId: 'a1-aone',
    storageBucket: 'a1-aone.firebasestorage.app',
    androidClientId: '834977391795-hc1sh43gq3an49jl1f8pm1jhq35m5tim.apps.googleusercontent.com',
    iosClientId: '834977391795-pt2pstr2ltn7okec4dtuspmg3qkp2633.apps.googleusercontent.com',
    iosBundleId: 'com.example.soloNetworkSns',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLQp_f0TaWMEX8mbzAucqw2GvO2w0Oy78',
    appId: '1:834977391795:web:3f62b68d4a058c06fd3cc6',
    messagingSenderId: '834977391795',
    projectId: 'a1-aone',
    authDomain: 'a1-aone.firebaseapp.com',
    storageBucket: 'a1-aone.firebasestorage.app',
    measurementId: 'G-0NL3YW9T34',
  );

}